name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-11

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run tests
      run: swift test --enable-test-discovery
