name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-12

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Lint code
      run: swift run swift-format --recursive Sources

    - name: Run tests
      run: swift test
